version: '3.7'
services:

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      - spark_network
  db:
    image: postgres:latest
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
    volumes:
    - pgdata:/var/lib/postgresql/data

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

networks:
  spark_network:
    driver: bridge
    name: spark_network

volumes:
  pgdata: